/**
 * API client for Flashcards endpoints
 */

export interface Flashcard {
  id: string;
  playId: string;
  assignmentId: string | null;
  position: string;
  category: string;
  cardType: 'assignment' | 'knowledge';
  questionPrompt: string;
  correctAnswer: string;
  hints: string[];
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  isAutoGenerated: boolean;
  isActive: boolean;
  createdAt: string;
  play: {
    id: string;
    name: string;
    formationName: string;
    concept: string;
    playType: string;
  };
}

export interface ListFlashcardsParams {
  orgId: string;
  playId?: string;
  position?: string;
  category?: string;
  cardType?: 'assignment' | 'knowledge';
  difficulty?: 'beginner' | 'intermediate' | 'advanced';
  activeOnly?: boolean;
  limit?: number;
  offset?: number;
}

class FlashcardsAPI {
  private getBaseURL(): string {
    // Check if we're running on localhost
    if (typeof window !== 'undefined') {
      const isLocalhost = window.location.hostname === 'localhost' ||
                         window.location.hostname === '127.0.0.1';

      if (isLocalhost) {
        // Use Netlify CLI dev server if available, otherwise direct functions
        return 'http://localhost:8888/.netlify/functions';
      }
    }

    // Use Netlify functions for production
    return '/.netlify/functions';
  }

  private async request<T>(
    endpoint: string,
    options: RequestInit = {}
  ): Promise<T> {
    const baseURL = this.getBaseURL();
    const response = await fetch(`${baseURL}/${endpoint}`, {
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({ error: response.statusText }));
      throw new Error(error.error || 'API request failed');
    }

    return response.json();
  }

  async listFlashcards(
    params: ListFlashcardsParams,
    token: string
  ): Promise<{ flashcards: Flashcard[]; total: number; limit: number; offset: number }> {
    const queryParams = new URLSearchParams();
    Object.entries(params).forEach(([key, value]) => {
      if (value !== undefined && value !== null) {
        queryParams.append(key, value.toString());
      }
    });

    return this.request(`flashcards-list?${queryParams.toString()}`, {
      method: 'GET',
      headers: { Authorization: `Bearer ${token}` },
    });
  }

  async regenerateFlashcards(
    playId: string,
    token: string
  ): Promise<{ success: boolean; message: string; playId: string }> {
    return this.request(`flashcards-regenerate/${playId}`, {
      method: 'POST',
      headers: { Authorization: `Bearer ${token}` },
    });
  }
}

export const flashcardsAPI = new FlashcardsAPI();
