/**
 * GET /api/flashcards
 * List flashcards from the question bank
 * Auth: Player+ (with filters based on role)
 */

import { Handler } from '@netlify/functions';
import { withOrgAuth, getAuthenticatedUser } from './shared/auth';
import { getSupabaseAdmin } from './shared/supabase';
import { formatErrorResponse, ValidationError } from './shared/errors';
import { validateUUID, validateEnum } from './shared/validators';

const handler: Handler = withOrgAuth('player')(async (event, context) => {
  if (event.httpMethod !== 'GET') {
    return {
      statusCode: 405,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ error: 'Method not allowed' }),
    };
  }

  try {
    const user = getAuthenticatedUser(event);
    const supabase = getSupabaseAdmin();
    const params = event.queryStringParameters || {};

    // Query parameters
    const orgId = params.orgId || user.orgId;
    validateUUID(orgId, 'orgId');

    // Verify orgId matches user's org
    if (orgId !== user.orgId) {
      throw new ValidationError('orgId must match your organization');
    }

    const playId = params.playId;
    const position = params.position;
    const category = params.category;
    const cardType = params.cardType; // 'assignment' or 'knowledge'
    const difficulty = params.difficulty; // 'beginner', 'intermediate', 'advanced'
    const activeOnly = params.activeOnly !== 'false'; // Default true
    const limit = params.limit ? parseInt(params.limit, 10) : 100;
    const offset = params.offset ? parseInt(params.offset, 10) : 0;

    // Validate filters
    if (playId) validateUUID(playId, 'playId');
    if (cardType) validateEnum(cardType, ['assignment', 'knowledge'], 'cardType');
    if (difficulty) validateEnum(difficulty, ['beginner', 'intermediate', 'advanced'], 'difficulty');

    // Build query - need to join with plays to filter by org_id
    let query = supabase
      .from('flashcard_templates')
      .select(`
        id,
        play_id,
        assignment_id,
        position,
        category,
        card_type,
        question_prompt,
        correct_answer,
        hints,
        difficulty,
        is_auto_generated,
        is_active,
        created_at,
        plays!inner (
          id,
          org_id,
          name,
          formation_name,
          concept,
          play_type,
          content_status,
          is_published
        )
      `, { count: 'exact' })
      .eq('plays.org_id', orgId)
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1);

    // Apply filters
    if (playId) {
      query = query.eq('play_id', playId);
    }

    if (position) {
      query = query.eq('position', position.toUpperCase());
    }

    if (category) {
      query = query.eq('category', category);
    }

    if (cardType) {
      query = query.eq('card_type', cardType);
    }

    if (difficulty) {
      query = query.eq('difficulty', difficulty);
    }

    if (activeOnly) {
      query = query.eq('is_active', true);
    }

    // Players only see flashcards from published, approved plays
    if (user.role === 'player') {
      query = query.eq('plays.is_published', true).eq('plays.content_status', 'approved');
    }

    const { data: flashcards, error: flashcardsError, count } = await query;

    if (flashcardsError) {
      throw new Error(`Failed to fetch flashcards: ${flashcardsError.message}`);
    }

    // Format response (flatten play data)
    const formattedFlashcards = (flashcards || []).map((fc: any) => ({
      id: fc.id,
      playId: fc.play_id,
      assignmentId: fc.assignment_id,
      position: fc.position,
      category: fc.category,
      cardType: fc.card_type,
      questionPrompt: fc.question_prompt,
      correctAnswer: fc.correct_answer,
      hints: fc.hints,
      difficulty: fc.difficulty,
      isAutoGenerated: fc.is_auto_generated,
      isActive: fc.is_active,
      createdAt: fc.created_at,
      play: {
        id: fc.plays.id,
        name: fc.plays.name,
        formationName: fc.plays.formation_name,
        concept: fc.plays.concept,
        playType: fc.plays.play_type,
      },
    }));

    console.log(`✅ Listed ${formattedFlashcards.length} flashcards for user ${user.userId}`);

    return {
      statusCode: 200,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        flashcards: formattedFlashcards,
        total: count || 0,
        limit,
        offset,
      }),
    };
  } catch (error) {
    console.error('Error listing flashcards:', error);
    return formatErrorResponse(error);
  }
});

export { handler };
