-- Migration: Add 'generating' to content_status constraint
-- This allows us to track plays that are currently being generated by AI

-- Drop the old constraint
ALTER TABLE plays DROP CONSTRAINT IF EXISTS chk_content_status;

-- Add the new constraint with 'generating' status
ALTER TABLE plays
  ADD CONSTRAINT chk_content_status
  CHECK (content_status IN ('draft', 'pending_review', 'approved', 'rejected', 'generating'));

-- Add comment explaining the statuses
COMMENT ON COLUMN plays.content_status IS
  'Status of play content:
  - generating: AI is currently generating content (background process)
  - draft: Content generated, awaiting review
  - pending_review: Submitted for review
  - approved: Content approved and published
  - rejected: Content rejected, needs regeneration';
